Add Lambda project type

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -95,6 +95,32 @@ runs:
       uses: docker/setup-buildx-action@v1
 
     #
+    # TYPE: LAMBDA
+    #
+
+    - name: install awscli
+      if: ${{ inputs.type == 'lambda' }}
+      shell: bash
+      run: |
+        if [ ${{ runner.arch }} = "ARM64" ]; then
+          ARCH="aarch64"
+        elif [ ${{ runner.arch }} = "X64" ]; then
+          ARCH="x86_64"
+        else
+          echo "::error title=unsupported cpu architecture"
+          exit 1
+        fi
+
+        curl -vfsSL \
+          "https://awscli.amazonaws.com/awscli-exe-linux-${arch}.zip" \
+          -o "/tmp/awscliv2.zip"
+
+        unzip "/tmp/awscliv2.zip"
+        ./aws/install
+        rm -rf "./aws"
+        rm -f "/tmp/awscliv2.zip"
+
+    #
     # TYPE: PYTHON
     #
 
